### ISSUE TITLE
Problem with sasquatch

### ISSUE THREAD

**Issue by dathannobrega** [ddcc/sasquatch#2]
I can't complete the sasquatch em my Debian 11:
follow the log on installation ->
$ sudo make install
make -C ./LZMA/lzmalt
make[1]: Entering directory '/home/vboxuser/Downloads/sasquatch/LZMA/lzmalt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/vboxuser/Downloads/sasquatch/LZMA/lzmalt'
make -C ./LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib
make[1]: Entering directory '/home/vboxuser/Downloads/sasquatch/LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/vboxuser/Downloads/sasquatch/LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib'
cc -g -O2  -I. -I./LZMA/lzma465/C -I./LZMA/lzmalt -I./LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DCOMP_DEFAULT=\"gzip\" -Wall -Werror  -DGZIP_SUPPORT -DLZMA_SUPPORT -DXZ_SUPPORT -DLZO_SUPPORT -DXATTR_SUPPORT -DXATTR_DEFAULT   -c -o lzma_wrapper.o lzma_wrapper.c
g++   ./LZMA/lzmalt/*.o unsquashfs.o unsquash-1.o unsquash-2.o unsquash-3.o unsquash-4.o swap.o compressor.o unsquashfs_info.o gzip_wrapper.o lzma_wrapper.o ./LZMA/lzma465/C/Alloc.o ./LZMA/lzma465/C/LzFind.o ./LZMA/lzma465/C/LzmaDec.o ./LZMA/lzma465/C/LzmaEnc.o ./LZMA/lzma465/C/LzmaLib.o xz_wrapper.o lzo_wrapper.o read_xattrs.o unsquashfs_xattr.o -lpthread -lm -lz -L./LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib -llzmalib  -llzma  -llzo2 -o sasquatch
/usr/bin/ld: unsquash-1.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: unsquash-2.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: unsquash-3.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: unsquash-4.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: compressor.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: unsquashfs_info.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: lzma_wrapper.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: read_xattrs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
/usr/bin/ld: unsquashfs_xattr.o:/home/vboxuser/Downloads/sasquatch/error.h:34: multiple definition of `verbose'; unsquashfs.o:/home/vboxuser/Downloads/sasquatch/error.h:34: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:298: sasquatch] Error 1

**Comment by satheshshiva** [comment]
This code change is a temporary workaround to fix this issue. https://github.com/firmadyne/sasquatch/pull/3

**Comment by dathannobrega** [comment]
Thanks
